default: &default
  pool: 5
  timeout: 5000
  username: root
  host: localhost

development:
  <<: *default
  adapter: mysql2
  database: db/twitter_development

production:
  adapter: postgresql
  <<: *default
  database: db/twitter_production
